#
# close-stale.yml
# Close open issues after a period of inactivity
#

name: Close Stale Issues

on:
  schedule:
  - cron: '22 1 * * 0'

jobs:
  stale:
    name: Close Stale Issues
    if: github.repository == 'classicrocker883/MRiscoCProUI'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity in the last 60 days. Please add a reply if you want to keep this issue active, otherwise it will be automatically closed within 10 days.'
        stale-pr-message: 'This pull request has had no activity in the last 60 days. Please update your branch.'
        close-issue-message: 'This issue was closed because it has had no activity in the last 10 days.'
        days-before-stale: 60
        days-before-close: 10
        days-before-pr-close: -1
        stale-issue-label: 'Stale'
        stale-pr-label: 'Stale'
        remove-stale-when-updated: true
        exempt-all-assignees: true
        exempt-issue-labels: 'bug,Feature Request,Needs: More Data,Needs: Discussion,Needs: Documentation,Needs: Patch,Needs: Work,Needs: Testing,help wanted,no-locking,work-in-progress'
        close-issue-reason: 'will not fix,false alarm,duplicate'
